version: '3'
services:
  db:
    container_name: kasm_db
    image: postgres:14-alpine
    healthcheck:
      test: "pg_isready --username=kasmapp && cat /proc/1/cmdline | grep -q '^postgres'"
      timeout: 5s
      retries: 20
    networks:
      - kasm_default_network
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: kasmapp
      POSTGRES_DB: kasm
    volumes:
      - /opt/kasm/1.16.0/conf/database/data.sql:/docker-entrypoint-initdb.d/data.sql
      - /opt/kasm/1.16.0/conf/database/pg_hba.conf:/var/lib/postgresql/conf/pg_hba.conf
      - /opt/kasm/1.16.0/conf/database/postgresql.conf:/var/lib/postgresql/conf/postgresql.conf
      - /opt/kasm/1.16.0/conf/database/:/tmp/
      - /opt/kasm/1.16.0/certs/db_server.crt:/etc/ssl/certs/db_server.crt
      - /opt/kasm/1.16.0/certs/db_server.key:/etc/ssl/certs/db_server.key
      - /opt/kasm/1.16.0/log/postgres/:/var/log/postgres/
      - kasm_db_1.16.0:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
    command: postgres -c ssl=on -c ssl_cert_file=/etc/ssl/certs/db_server.crt -c ssl_key_file=/etc/ssl/certs/db_server.key -c config_file=/var/lib/postgresql/conf/postgresql.conf -c hba_file=/var/lib/postgresql/conf/pg_hba.conf
    restart: "always"
  kasm_redis:
    container_name: kasm_redis
    command: ["sh", "-c", "redis-server --requirepass $${REDIS_PASSWORD}"]
    user: "${KASM_UID?}:${KASM_GID?}"
    image: redis:5-alpine
    networks:
      - kasm_default_network
    environment:
      REDIS_PASSWORD: changeme
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
    restart: "always"
  kasm_api:
    container_name: kasm_api
    user: "${KASM_UID?}:${KASM_GID?}"
    image: "kasmweb/api:1.16.0"
    read_only: true
    networks:
      - kasm_default_network
    volumes:
      - /opt/kasm/1.16.0:/opt/kasm/current
      - /opt/kasm/1.16.0/tmp/api:/tmp
    depends_on:
      - db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
  kasm_manager:
    container_name: kasm_manager
    user: "${KASM_UID?}:${KASM_GID?}"
    image: "kasmweb/manager:1.16.0"
    read_only: true
    networks:
      - kasm_default_network
    volumes:
      - /opt/kasm/1.16.0:/opt/kasm/current
      - /opt/kasm/1.16.0/tmp/manager:/tmp
    depends_on:
      - db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
  kasm_agent:
    container_name: kasm_agent
    user: root
    image: "kasmweb/agent:1.16.0"
    read_only: true
    networks:
      - kasm_default_network
    volumes:
      - /opt/kasm/1.16.0:/opt/kasm/current
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/kasm/1.16.0/conf/nginx:/etc/nginx/conf.d
    depends_on:
      - kasm_manager
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
  kasm_share:
    container_name: kasm_share
    user: root
    image: "kasmweb/share:1.16.0"
    read_only: true
    networks:
      - kasm_default_network
    volumes:
      - /opt/kasm/1.16.0:/opt/kasm/current
    restart: always
    depends_on:
      - db
      - kasm_redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
  kasm_guac:
    container_name: kasm_guac
    user: "${KASM_UID?}:${KASM_GID?}"
    image: "kasmweb/kasm-guac:1.16.0"
    read_only: true
    networks:
      - kasm_default_network
    volumes:
      - /opt/kasm/1.16.0/log:/opt/kasm/current/log
      - /opt/kasm/1.16.0/tmp/guac:/opt/kasm/current/tmp/guac
      - /opt/kasm/1.16.0/conf/app/kasmguac.app.config.yaml:/opt/kasm/current/conf/app/kasmguac.app.config.yaml
      - /opt/kasm/1.16.0/tmp/guac:/tmp
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
  rdp_gateway:
    container_name: kasm_rdp_gateway
    image: "kasmweb/rdp-gateway:1.16.0"
    user: "${KASM_UID?}:${KASM_GID?}"
    read_only: true
    depends_on:
      - kasm_api
    ports:
      - "3389:3389"
    networks:
      - kasm_default_network
    volumes:
      - /opt/kasm/1.16.0/log:/opt/kasm/current/log
      - /opt/kasm/1.16.0/conf/app/rdpproxy.ini:/usr/local/etc/rdpproxy/rdpproxy.ini
      - /opt/kasm/1.16.0/conf/app/passthrough.app.config.yaml:/usr/local/etc/rdpproxy/passthrough.app.config.yaml
      - /opt/kasm/1.16.0/certs/kasm_nginx.key:/usr/local/etc/rdpproxy/rdpproxy.key
      - /opt/kasm/1.16.0/certs/kasm_nginx.crt:/usr/local/etc/rdpproxy/rdpproxy.crt
      - /opt/kasm/1.16.0/tmp/rdpgw/var:/usr/local/etc/rdpproxy/var
      - /opt/kasm/1.16.0/tmp/rdpgw/tmp:/tmp
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
  kasm_rdp_https_gateway:
    container_name: kasm_rdp_https_gateway
    image: "kasmweb/rdp-https-gateway:1.16.0"
    user: "${KASM_UID?}:${KASM_GID?}"
    read_only: true
    depends_on:
      - rdp_gateway
    networks:
      - kasm_default_network
    volumes:
      - /opt/kasm/1.16.0/log:/opt/kasm/current/log
      - /opt/kasm/1.16.0/conf/app/rdp_https_gateway.app.config.yaml:/opt/rdpgw/rdpgw_kasm.yaml
      - /opt/kasm/1.16.0/conf/app/rdpgw.yaml:/opt/rdpgw/rdpgw.yaml
      - /opt/kasm/1.16.0/certs/kasm_nginx.key:/opt/rdpgw/key.pem
      - /opt/kasm/1.16.0/certs/kasm_nginx.crt:/opt/rdpgw/server.pem
    restart: always
  proxy:
    container_name: kasm_proxy
    image: "kasmweb/proxy:1.16.0"
    ports:
      - "443:443"
    networks:
      - kasm_default_network
      - kasm_sidecar_network
    volumes:
      - /opt/kasm/1.16.0/conf/nginx:/etc/nginx/conf.d:ro
      - /opt/kasm/1.16.0/certs/kasm_nginx.key:/etc/ssl/private/kasm_nginx.key
      - /opt/kasm/1.16.0/certs/kasm_nginx.crt:/etc/ssl/certs/kasm_nginx.crt
      - /opt/kasm/1.16.0/log/nginx:/var/log/external/nginx/
      - /opt/kasm/1.16.0/log/logrotate:/var/log/external/logrotate/
    depends_on:
      - kasm_manager
      - kasm_api
      - kasm_agent
      - kasm_share
      - kasm_guac
      - kasm_rdp_https_gateway
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
volumes:
  kasm_db_1.16.0:
    external: true

networks:
  kasm_default_network:
    external: true
  kasm_sidecar_network:
    external: true
